Repository polkadot-js/api, pull requests merged in 2018-12, with the labels that each got.

#432 Tuple extends Array
  docs/examples/promise/08_system_events/index.js
  packages/api-observable/src/classes.ts
  packages/types/src/Bft.spec.ts
  packages/types/src/Bft.ts
  packages/types/src/Digest.ts
  packages/types/src/Event.ts
  packages/types/src/Justification.spec.ts
  packages/types/src/KeyValue.spec.ts
  packages/types/src/KeyValue.ts
  packages/types/src/Metadata.ts
  packages/types/src/MisbehaviorReport.spec.ts
  packages/types/src/RuntimeVersion.ts
  packages/types/src/StorageChangeSet.spec.ts
  packages/types/src/StoredPendingChange.ts
  packages/types/src/codec/Tuple.spec.ts
  packages/types/src/codec/Tuple.ts
  packages/types/src/codec/Vector.spec.ts
  packages/types/src/codec/createType.ts
Labels: @types

#436 Expose map and filter on Tuple
  packages/types/src/codec/Tuple.spec.ts
  packages/types/src/codec/Tuple.ts
Labels: @types

#451 [CI Skip] Update .codeclimate.yml ignorning *.spec.ts
  .codeclimate.yml
Labels: insubstantial

#455 Bump dependencies
  package.json
  packages/api-observable/package.json
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#456 Update types parsing to latest metadata
  packages/types/src/Metadata/latest.json
  packages/types/src/Type.spec.ts
  packages/types/src/Type.ts
  packages/types/src/json/Metadata.latest.json
Labels: @types

#466 Add types from latest metadata
  packages/types/src/InherentOfflineReport.ts
  packages/types/src/Metadata/index.ts
  packages/types/src/Metadata/latest.json
  packages/types/src/ReferendumInfo.ts
  packages/types/src/Type.spec.ts
  packages/types/src/Type.ts
  packages/types/src/codec/createType.spec.ts
  packages/types/src/codec/createType.ts
  packages/types/src/index.ts
  packages/types/src/json/Metadata.latest.json
Labels: @types

#471 Bump API version on examples (updated metadata parsing)
  docs/examples/promise/01_simple_connect/package.json
  docs/examples/promise/02_listen_to_blocks/package.json
  docs/examples/promise/03_listen_to_balance_change/package.json
  docs/examples/promise/05_read_storage/package.json
  docs/examples/promise/07_transfer_dots/package.json
  docs/examples/promise/08_system_events/package.json
Labels: insubstantial

#482 Bump common (TextEncoder/Decoder polyfill)
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#485 Add explicit core-js dep (& bump common)
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#487 Bump common
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#483 Factorize some u8a decoding logic
  packages/types/src/codec/Struct.ts
  packages/types/src/codec/Tuple.ts
  packages/types/src/codec/Vector.ts
  packages/types/src/codec/utils/decodeU8a.ts
Labels: @types

#486 Return { status: ExtrinsicStatus } from tx send subscription
  CHANGELOG.md
  lerna.json
  packages/api-observable/package.json
  packages/api/package.json
  packages/api/src/promise/SubmittableExtrinsic.ts
  packages/api/src/rx/SubmittableExtrinsic.ts
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: breaking change

#502 Bump deps
  package.json
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#484 Add support for default values
  packages/type-extrinsics/src/fromMetadata.spec.ts
  packages/type-extrinsics/src/index.spec.ts
  packages/types/src/Extrinsic.spec.ts
  packages/types/src/Metadata/Metadata.spec.ts
  packages/types/src/Metadata/Modules.ts
  packages/types/src/Metadata/latest.substrate.json
  packages/types/src/Metadata/static.ts
  packages/types/src/Method.spec.ts
  packages/types/src/SignedBlock.spec.ts
  packages/types/src/codec/Tuple.spec.ts
  packages/types/src/codec/Vector.spec.ts
  packages/types/src/json/Metadata.latest.json
Labels: @types, breaking change

#507 Bump package (should have been done with metadata, breaking)
  CHANGELOG.md
  lerna.json
  package.json
  packages/api-observable/package.json
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#508 Pull in large-value Compact encoding changes
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  packages/types/src/codec/Compact.spec.ts
  yarn.lock
Labels: insubstantial

#511 Update to latest util for Compact
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  packages/types/src/codec/Compact.spec.ts
  packages/types/src/codec/Compact.ts
  yarn.lock
Labels: insubstantial
