Repository polkadot-js/api, pull requests merged in 2019-02, with the labels that each got.

#690 Increase time periods in drr test for more consistent results
  packages/api-derive/src/util/drr.spec.ts
Labels: @api-derive

#672 [Docs] Add info on how to add custom types to API
  packages/api/README.md
Labels: documentation

#700 Bump (schnorrkel webpack warning)
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#717 Handle storage with optional modifiers
  CHANGELOG.md
  lerna.json
  packages/api-derive/package.json
  packages/api-derive/src/democracy/referendumInfo.ts
  packages/api-derive/src/democracy/referendumInfos.ts
  packages/api-derive/src/democracy/referendums.ts
  packages/api-derive/src/session/sessionProgress.ts
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-core/src/formatting.spec.ts
  packages/rpc-core/src/index.spec.ts
  packages/rpc-core/src/index.ts
  packages/rpc-core/src/methodSend.spec.ts
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/type-storage/src/substrate.ts
  packages/types/package.json
  packages/types/src/Metadata/v0/Modules.ts
  packages/types/src/Metadata/v1/toV0.ts
  packages/types/src/codec/AbstractInt.ts
  packages/types/src/codec/Compact.ts
  packages/types/src/codec/Enum.spec.ts
  packages/types/src/codec/Enum.ts
  packages/types/src/codec/EnumType.ts
  packages/types/src/codec/Option.ts
  packages/types/src/codec/Struct.ts
  packages/types/src/codec/Tuple.ts
  packages/types/src/codec/Vector.ts
  packages/types/src/codec/index.ts
  packages/types/src/primitive/Bool.ts
  packages/types/src/primitive/Moment.ts
  packages/types/src/primitive/Null.ts
  packages/types/src/primitive/Text.ts
  packages/types/src/scripts/MetadataMd.ts
  packages/types/src/type/Address.ts
  packages/types/src/type/ChainProperties.ts
  packages/types/src/types.ts
Labels: breaking change

#728 Bump common
  package.json
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#734 Update type documentation links
  docs/SUMMARY.md
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/README.md
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#737 Bump deps
  .travis.yml
  package.json
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial
