Repository polkadot-js/api, pull requests merged in 2019-01, with the labels that each got.

#527 Subscriptions return unsubscribe/dispose function
  CHANGELOG.md
  lerna.json
  packages/api-observable/package.json
  packages/api/package.json
  packages/api/src/promise/Combinator.ts
  packages/api/src/promise/Combinators.spec.ts
  packages/api/src/promise/SubmittableExtrinsic.ts
  packages/api/src/promise/index.ts
  packages/api/src/promise/types.ts
  packages/api/src/types.ts
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
  packages/types/src/scripts/MetadataMd.ts
  yarn.lock
Labels: @api, breaking change

#528 Update API Promise combineLatest signature
  packages/api/src/promise/index.ts
  packages/api/src/promise/types.ts
Labels: insubstantial

#531 Bump deps
  package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#543 Add length prefix manually (sample)
  docs/examples/promise/10_upgrade_chain/README.md
  docs/examples/promise/10_upgrade_chain/index.js
Labels: insubstantial

#545 Expose status from result, remove now-unused api-observable docs
  docs/api-observable/README.md
  docs/api-observable/SUMMARY.md
  docs/api-observable/classes/_base_.apibase.md
  docs/api-observable/classes/_calls_.apicalls.md
  docs/api-observable/classes/_classes_.rxproposal.md
  docs/api-observable/classes/_classes_.rxproposaldeposits.md
  docs/api-observable/classes/_combined_.apicombined.md
  docs/api-observable/classes/_index_.api.md
  docs/api-observable/classes/_queries_.apiqueries.md
  docs/api-observable/modules/_base_.md
  docs/api-observable/modules/_calls_.md
  docs/api-observable/modules/_classes_.md
  docs/api-observable/modules/_combined_.md
  docs/api-observable/modules/_index_.md
  docs/api-observable/modules/_queries_.md
  docs/api-observable/modules/_types_.md
  docs/examples/promise/10_upgrade_chain/index.js
Labels: insubstantial

#550 Update metadata
  packages/types/src/Metadata/latest.substrate.json
  packages/types/src/Metadata/static.ts
Labels: @types

#551 Compact<Index> minor bump, update CHANGELOG
  CHANGELOG.md
  lerna.json
  packages/api/package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
Labels: breaking change, insubstantial

#556 Add link to api-derive in README
  README.md
Labels: insubstantial

#561 Add api-derive dep
  packages/api/package.json
Labels: insubstantial

#562 Upgrade test with real wasm (via sudo now)
  docs/SUMMARY.md
  docs/examples/promise/01_simple_connect/package.json
  docs/examples/promise/02_listen_to_blocks/package.json
  docs/examples/promise/03_listen_to_balance_change/package.json
  docs/examples/promise/05_read_storage/package.json
  docs/examples/promise/07_transfer_dots/package.json
  docs/examples/promise/08_system_events/package.json
  docs/examples/promise/09_transfer_events/package.json
  docs/examples/promise/10_upgrade_chain/README.md
  docs/examples/promise/10_upgrade_chain/index.js
  docs/examples/promise/10_upgrade_chain/package.json
  docs/examples/promise/10_upgrade_chain/test.wasm
Labels: insubstantial

#570 Fix CI publish
  .gitignore
  package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#572 Allow handling of RPC errors, promise resolve/reject
  CHANGELOG.md
  lerna.json
  packages/api-derive/package.json
  packages/api/package.json
  packages/api/src/promise/SubmittableExtrinsic.ts
  packages/api/src/promise/index.ts
  packages/api/src/promise/types.ts
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
Labels: breaking change

#586 Bump deps
  package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#566 Refactor api-promise/rx
  CHANGELOG.md
  lerna.json
  packages/api-derive/package.json
  packages/api-derive/src/balances/accountIdAndIndex.ts
  packages/api-derive/src/balances/accountIdToIndex.ts
  packages/api-derive/src/balances/accountIndexToId.ts
  packages/api-derive/src/balances/accountIndexes.ts
  packages/api-derive/src/balances/fees.ts
  packages/api-derive/src/balances/validatingBalance.ts
  packages/api-derive/src/balances/validatingBalances.ts
  packages/api-derive/src/balances/votingBalance.ts
  packages/api-derive/src/balances/votingBalances.ts
  packages/api-derive/src/balances/votingBalancesNominatorsFor.ts
  packages/api-derive/src/chain/bestNumber.ts
  packages/api-derive/src/chain/bestNumberFinalised.ts
  packages/api-derive/src/democracy/referendumInfos.ts
  packages/api-derive/src/democracy/referendumVotesFor.ts
  packages/api-derive/src/democracy/referendums.ts
  packages/api-derive/src/democracy/votes.ts
  packages/api-derive/src/index.spec.ts
  packages/api-derive/src/index.ts
  packages/api-derive/src/session/eraLength.ts
  packages/api-derive/src/session/eraProgress.ts
  packages/api-derive/src/session/sessionProgress.ts
  packages/api-derive/src/util/cache.spec.ts
  packages/api-derive/src/util/cache.ts
  packages/api-derive/test/e2e/derive.spec.ts
  packages/api/package.json
  packages/api/src/Base.ts
  packages/api/src/SubmittableExtrinsic.ts
  packages/api/src/promise/SubmittableExtrinsic.spec.ts
  packages/api/src/promise/SubmittableExtrinsic.ts
  packages/api/src/promise/index.ts
  packages/api/src/promise/types.ts
  packages/api/src/rx/SubmittableExtrinsic.ts
  packages/api/src/rx/index.ts
  packages/api/src/rx/types.ts
  packages/api/src/types.ts
  packages/api/test/e2e/promise-queries.spec.js
  packages/api/test/e2e/promise-tx.spec.js
  packages/api/test/e2e/rx-queries.spec.js
  packages/api/test/e2e/rx-tx.spec.js
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
Labels: breaking change, refactor

#599 Bump deps
  package.json
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/type-extrinsics/package.json
  packages/type-storage/package.json
  packages/types/package.json
  yarn.lock
Labels: insubstantial

#619 Bump dev dependency (fix for doc generation)
  package.json
  yarn.lock
Labels: insubstantial

#620 [Docs] change headline on ApiRx index page
  docs/examples/rx/README.md
Labels: insubstantial

#631 Revert "Bubble isSubscription from rpc-rx (#627)"
  packages/api/src/promise/index.ts
  packages/api/test/e2e/promise-queries.spec.js
  packages/api/test/e2e/promise-tx.spec.js
  packages/api/test/e2e/rx-queries.spec.js
  packages/api/test/e2e/rx-tx.spec.js
  packages/rpc-rx/src/index.ts
  packages/rpc-rx/src/types.ts
Labels: insubstantial

#643 Use memoizee instead of custom cache
  package.json
  packages/rpc-rx/package.json
  packages/rpc-rx/src/cached.spec.ts
  packages/rpc-rx/src/index.spec.ts
  packages/rpc-rx/src/index.ts
  packages/rpc-rx/src/replay.spec.ts
  packages/rpc-rx/src/types.ts
  yarn.lock
Labels: @rpc-rx

#653 Comment around padding of seeds
  docs/examples/promise/06_make_transfer/index.js
Labels: insubstantial

#655 Cater for signature over hash (with version checks)
  CHANGELOG.md
  docs/examples/promise/09_transfer_events/index.js
  lerna.json
  packages/api-derive/package.json
  packages/api/package.json
  packages/api/src/Base.ts
  packages/api/src/SubmittableExtrinsic.ts
  packages/api/src/promise/index.ts
  packages/api/src/rx/index.ts
  packages/api/test/e2e/promise-tx.spec.js
  packages/api/test/e2e/rx-tx.spec.js
  packages/rpc-core/package.json
  packages/rpc-provider/package.json
  packages/rpc-rx/package.json
  packages/type-extrinsics/package.json
  packages/type-extrinsics/src/index.spec.ts
  packages/type-extrinsics/test/e2e/transfer.spec.js
  packages/type-jsonrpc/package.json
  packages/type-storage/package.json
  packages/types/package.json
  packages/types/src/Extrinsic.ts
  packages/types/src/ExtrinsicSignature.ts
  packages/types/src/SignaturePayload.ts
Labels: breaking change
